# -*- coding: utf-8 -*-
"""Task 6.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xk0ghKjMG48WVMkCwLElaLSdflp3dTdO

The main goal is to train an ANN (Artificial Neural Network) to predict whether a mobile phone belongs to:

1 → High price
0 → Low price
upload the CSV file and check the column
"""

from google.colab import files
import io

print('Please upload the CSV file:')
uploaded = files.upload()

# Assuming only one file is uploaded, get its name
if uploaded:
    uploaded_filename = next(iter(uploaded))
    print(f'File "{uploaded_filename}" uploaded successfully.')
else:
    uploaded_filename = None
    print('No file was uploaded.')

"""After uploading the file, the next cell will be updated to use the uploaded file's name. Please run the previous cell first, upload your file, and then run the next cell."""

import pandas as pd

# Ensure 'uploaded_filename' is defined from the previous upload cell
if 'uploaded_filename' in locals() and uploaded_filename:
    df = pd.read_csv(uploaded_filename)
    display(df.head())
else:
    print("Please run the file upload cell first and upload your CSV file.")

df.columns

"""Step 2 — Separate Features (X) and Target (Y)
dataset should have a column representing the price range, usually:

*price_range*

X = mobile phone features such as RAM, battery power, internal memory, etc.
Y = price_range (0 or 1)
"""

X = df.drop("price_range", axis=1)
Y = df["price_range"]

print(X.shape)
print(Y.shape)

"""Step 3 — Split Training and Testing Data
75% training and 25% testing
"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, Y,
    test_size=0.25,
    random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

"""Step 4 — Create ANN Model
1st hidden layer → 8 neurons
2nd hidden layer → 4 neurons
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

model.add(Dense(8, activation='relu', input_shape=(X_train.shape[1],)))

model.add(Dense(4, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

model.summary()

"""Step 5 — Compile the Model
binary classification problem, use binary_crossentropy.
"""

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

"""Step 6 — Train for 100 Epochs
100 epochs and batch size 32
"""

history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=32,
    validation_data=(X_test, y_test)
)

"""Step 7 — Check Accuracy"""

loss, accuracy = model.evaluate(X_test, y_test)

print("Test Accuracy:", accuracy)

"""Step 8 — Save the Weights"""

model.save_weights("mobile_price_model.weights.h5")